[package]
name = "dropboxignore"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
xattr = { version = "1.3.1", default-features = false, features = ["unsupported"] }

# we really ony care about a subsert of this, but for now we need to bring in all the deps of it
ignore = "0.4"
